title: Krishna R # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Frontend Engineer
  <br><br>
  <a href="mailto: jiophoneoct21@gmail.com">jiophoneoct21@gmail.com </a>
  <br>
  
  <br>
  <a href="https://www.github.com/krishna1206/">Github</a> 
theme: jekyll-theme-minimal
